"""
Core event types for multi-agent trading system with complete lifecycle tracking.
"""

# Order lifecycle events
ORDER_PROPOSED = "ORDER_PROPOSED"
ORDER_VALIDATED = "ORDER_VALIDATED"
ORDER_SUBMITTED = "ORDER_SUBMITTED"
ORDER_OPENED = "ORDER_OPENED"
ORDER_PARTIALLY_FILLED = "ORDER_PARTIALLY_FILLED"
ORDER_FILLED = "ORDER_FILLED"
ORDER_CLOSED = "ORDER_CLOSED"
ORDER_CANCELLED = "ORDER_CANCELLED"
ORDER_REJECTED = "ORDER_REJECTED"

# Position events
POSITION_UPDATED = "POSITION_UPDATED"
POSITION_PARTIAL_CLOSE = "POSITION_PARTIAL_CLOSE"
POSITION_CLOSED = "POSITION_CLOSED"
POSITION_LIQUIDATED = "POSITION_LIQUIDATED"

# Take Profit / Stop Loss events
TP_HIT = "TP_HIT"
SL_HIT = "SL_HIT"
TRAILING_STOP_UPDATED = "TRAILING_STOP_UPDATED"

# Sync events
SYNC_RECEIVED = "SYNC_RECEIVED"
SYNC_MISMATCH = "SYNC_MISMATCH"
SYNC_REPAIRED = "SYNC_REPAIRED"
RECONCILIATION_STARTED = "RECONCILIATION_STARTED"
RECONCILIATION_COMPLETED = "RECONCILIATION_COMPLETED"

# System events
API_ERROR = "API_ERROR"
WEBSOCKET_DISCONNECTED = "WEBSOCKET_DISCONNECTED"
WEBSOCKET_RECONNECTED = "WEBSOCKET_RECONNECTED"
RECOVERY_STARTED = "RECOVERY_STARTED"
RECOVERY_COMPLETED = "RECOVERY_COMPLETED"

# Notification events
TELEGRAM_SENT = "TELEGRAM_SENT"
TELEGRAM_FAILED = "TELEGRAM_FAILED"
DAILY_SUMMARY_READY = "DAILY_SUMMARY_READY"
