"""
Strategy Manager - Orchestrates multiple strategies and selects optimal signals.

Responsibilities:
- Load and initialize all available strategies
- Run strategies in parallel on market data
- Select highest-confidence signal
- Apply AI filter validation
"""
from typing import Dict, Any, List, Optional
from app.strategy.base_strategy import BaseStrategy
from app.strategy.signal_proposal import SignalProposal
from app.strategy.breakout import BreakoutStrategy
from app.strategy.mean_reversion import MeanReversionStrategy
from app.strategy.trend import TrendStrategy
from app.strategy.ai_filter import AIFilter
from app.logging_config import get_logger
import asyncio

logger = get_logger(__name__)

class StrategyManager:
    """Manages multiple trading strategies and signal selection."""
    
    def __init__(self, use_ai_filter: bool = True):
        self.strategies: List[BaseStrategy] = [
            BreakoutStrategy(),
            MeanReversionStrategy(),
            TrendStrategy()
        ]
        self.ai_filter = AIFilter() if use_ai_filter else None
        logger.info(f"✅ Strategy Manager initialized with {len(self.strategies)} strategies")
    
    async def generate_signals(self, market_data: Dict[str, Any]) -> Optional[SignalProposal]:
        """
        Run all strategies and return best signal.
        
        Args:
            market_data: Market snapshot with indicators
            
        Returns:
            Best signal proposal (highest confidence after AI filtering)
        """
        try:
            # Run all strategies in parallel
            tasks = [strategy.generate_signal(market_data) for strategy in self.strategies]
            results = await asyncio.gather(*tasks, return_exceptions=True)
            
            # Filter out None and exceptions
            valid_signals = []
            for i, result in enumerate(results):
                if isinstance(result, Exception):
                    logger.warning(f"Strategy {self.strategies[i].name} error: {result}")
                elif result is not None:
                    valid_signals.append(result)
            
            if not valid_signals:
                logger.debug("No signals generated by any strategy")
                return None
            
            logger.info(f"[SIGNAL] Generated {len(valid_signals)} raw signals from {len(self.strategies)} strategies")
            for i, sig in enumerate(valid_signals):
                logger.info(
                    f"[SIGNAL #{i+1}] {sig.strategy_name} | {sig.symbol} | "
                    f"{sig.side} @ ${sig.entry_price:,.2f} | "
                    f"Confidence: {sig.confidence:.2%}"
                )
            
            # Apply AI filter if enabled
            if self.ai_filter:
                market_context = {
                    'regime': market_data.get('regime', 'Normal'),
                    'volatility': market_data.get('volatility', 0.5),
                    'volume_trend': market_data.get('volume_trend', 'neutral')
                }
                
                filtered_signals = []
                for signal in valid_signals:
                    validated = await self.ai_filter.validate_signal(signal, market_context)
                    if validated:
                        filtered_signals.append(validated)
                
                valid_signals = filtered_signals
            
            if not valid_signals:
                logger.info("All signals filtered out by AI")
                return None
            
            # Select highest confidence signal
            best_signal = max(valid_signals, key=lambda s: s.confidence)
            
            logger.info(f"Selected best signal: {best_signal.strategy_name} "
                       f"({best_signal.side}) with confidence {best_signal.confidence}")
            
            return best_signal
            
        except Exception as e:
            logger.error(f"Strategy Manager error: {e}")
            return None
    
    def get_strategy_info(self) -> List[Dict[str, Any]]:
        """Get information about all loaded strategies."""
        return [
            {
                'name': strategy.name,
                'parameters': strategy.get_parameters()
            }
            for strategy in self.strategies
        ]
